### ISSUE TITLE
Cloud Storage and Document Submission

### ISSUE THREAD

**Issue by bcdevex** [bcgov/gwells#1036]
<p>This issue has been auto-generated to facilitate questions about <a href="https://bcdevexchange.org/opportunities/cwu/opp-cloud-storage-and-document-submission">a paid opportunity</a> that has just been posted on the <a href="https://bcdevexchange.org">BCDevExchange</a>.</p><p>To learn more or apply, <a href="https://bcdevexchange.org/opportunities/cwu/opp-cloud-storage-and-document-submission">visit the opportunity page</a>. The opportunity closes on <b>Saturday, December 8, 2018</b>.</p>

**Comment by LindsayMacfarlane** [comment]
Thank you to all those that responded to this opportunity. Based on our evaluation criteria @sjrumsby  scored the highest and has been assigned.

If you would like feedback on your proposal, we can provide that. Please contact me by the email address in my profile. https://bcdevexchange.org/projects/prj-gwells
