### ISSUE TITLE
Groundwater Wells (GWELLS) - Custom Search and Interactive Map

### ISSUE THREAD

**Issue by bcdevex** [bcgov/gwells#1101]
<p>This issue has been auto-generated to facilitate questions about <a href="https://bcdevexchange.org/opportunities/cwu/opp-groundwater-wells--gwells----custom-search">a paid opportunity</a> that has just been posted on the <a href="https://bcdevexchange.org">BCDevExchange</a>.</p><p>To learn more or apply, <a href="https://bcdevexchange.org/opportunities/cwu/opp-groundwater-wells--gwells----custom-search">visit the opportunity page</a>. The opportunity closes on <b>Saturday, January 26, 2019</b>.</p>

**Comment by LindsayMacfarlane** [comment]
Hello! @ashleydhillon and myself are the main contacts for this code with us opportunity. Please feel free to reach out to us with any questions you may have about this opportunity and we will do our best to respond as soon as possible.

**Comment by mark-a-wilson** [comment]
Hello all interested applicants. Please note that the **closing deadline** for proposals is **January 25, 2019** at **4:00 PM PST** (as stated on the [opportunity page](https://www.bcdevexchange.org/opportunities/cwu/opp-groundwater-wells--gwells----custom-searchl)), NOT Jan 26 as stated at the beginning of this thread. (Bug with the BCDX app) Apologies! 🙏

**Comment by LindsayMacfarlane** [comment]
We would not be expecting real-time searching, but the API should include functions to filter and order the results.

We would hope the successful candidate would work with the team to determine the best approach. 

As an FYI - the data set includes about 110,000 wells and that number grows on a daily basis so this could affect the approach taken/proposed.

**Comment by bcdevex** [comment]
This opportunity has been assigned

**Comment by ashleydhillon** [comment]
We want to thank everyone who submitted proposals for this opportunity. For the unsuccessful candidates, if you'd like to have feedback, please don't hesitate to contact @LindsayMacfarlane or @ashleydhillon.

**Comment by mark-a-wilson** [comment]
Hey @ashleydhillon - presuming that closing this issue means that work is complete and you'll be paying the full amount? (Thanks for confirming ... just following up on tracking _Code With Us_ opportunities.)

**Comment by ashleydhillon** [comment]
Hi @mark-a-wilson - yes that's correct. I'm hoping this is the last step but please let me know if there's anything else I should be doing :) Thanks!
