### ISSUE TITLE
Aquifer Summary and Interactive Map

### ISSUE THREAD

**Issue by bcdevex** [bcgov/gwells#1138]
<p>This issue has been auto-generated to facilitate questions about
<a href="https://bcdevexchange.org/opportunities/cwu/opp-aquifer-summary--interactive-map-and-report"> a paid opportunity</a> that has just been posted on the
<a href="https://bcdevexchange.org">BCDevExchange</a>.</p>

<p>To learn more or apply, <a href="https://bcdevexchange.org/opportunities/cwu/opp-aquifer-summary--interactive-map-and-report">visit the opportunity page</a>.
The opportunity closes on <b>Sunday, February 17th, 2019 at 16:00 PST</b>.</p>

**Comment by LindsayMacfarlane** [comment]
Hello! @ashleydhillon and myself are the main contacts for this code with us opportunity. Please feel free to reach out to us with any questions you may have about this opportunity and we will do our best to respond as soon as possible.

**Comment by tansaku** [comment]
hi @LindsayMacfarlane and @ashleydhillon - we were just wondering if you have some graphical mockups of how you want the interface to change?  The milestones provided and very detailed and comprehensive, but are you imagining a particular layout?  Or would you like the developers to come up with multiple alternatives for you to consider?

**Comment by LindsayMacfarlane** [comment]
Hi @tansaku - thanks for the question! You can find our mockup on our project Trello board  [https://trello.com/c/df1aSfr8](url). Please note, the mockups are specific for the search, entry/edit, summary page and map (they don't include the uploading of the shapefiles).

**Comment by tansaku** [comment]
thanks @LindsayMacfarlane - that's very helpful :-)

**Comment by tansaku** [comment]
hi @LindsayMacfarlane @Ashley-Ward any word on this project? Did it get assigned?

**Comment by bcdevex** [comment]
This opportunity has been assigned

**Comment by LindsayMacfarlane** [comment]
We want to thank everyone who submitted proposals for this opportunity. For the unsuccessful candidates, if you'd like to have feedback, please don't hesitate to contact @LindsayMacfarlane or @ashleydhillon.

**Comment by tansaku** [comment]
thanks @LindsayMacfarlane and @ashleydhillon - we'd love to get feedback - what's the best way to contact you? there are no email addresses on your github profiles

**Comment by ashleydhillon** [comment]
Hi @tansaku I'll send over a meeting invite this week for us to discuss. Stay tuned for an invite coming your way shortly. Thanks!
