### ISSUE TITLE
All attachments disappear when new attachment added

### ISSUE THREAD

**Issue by LolandaE** [bcgov/gwells#1812]
**Describe the Bug**
When new attachments are added to records all of the attachments disappear. When you return to the well summary after editing it shows "Unable to retrieve file list." When you go back into edit it does not show any attachments. 

Initially found with WTN 67013. Noticed the same thing with WTN 114569 and WTN 123917.

**Expected Behaviour**
When an attachment is added, it is added and all attachments are preserved.

**Actual Behaviour**
When an attachment is added, other attachments are removed. When they go to view attachments, they can only see the existence of them in "edit" mode. 

** Steps To Reproduce**
Look at images below

![image.png](https://images.zenhubusercontent.com/624f2ed04f19a502bdf062d9/d74a3336-2829-4a0c-ba92-ec35ee1dfd34)

![image.png](https://images.zenhubusercontent.com/624f2ed04f19a502bdf062d9/fa063fdf-1f97-49d0-854a-c2c392e2f397)

![image.png](https://images.zenhubusercontent.com/624f2ed04f19a502bdf062d9/68c51b39-9e25-41e1-b4cd-9471adf60171)

![image.png](https://images.zenhubusercontent.com/624f2ed04f19a502bdf062d9/517c0510-868b-4678-99a5-853e45943377)

![image.png](https://images.zenhubusercontent.com/624f2ed04f19a502bdf062d9/906d726b-adbf-4eed-8701-12997706e4be)

**Comment by LolandaE** [comment]
Investigate in OpenShift

**Comment by carmenriddel** [comment]
Another important aspect of this bug is that before you see the "Unable to Retrieve File List" message, there is usually a perpetual spinning wheel and a "Loading Documents". 

The workaround is to refresh the page a few times and the documents will eventually sh![LoadDoc.PNG](https://images.zenhubusercontent.com/6298f5b38f739f6b28b0fa63/e53a3c7c-321b-4d71-89f9-65644fad0844)ow up.

**Comment by LolandaE** [comment]
Hey @Uelunt - we're wondering why this ticket was re-opened. Is there an issue we need to know about?

**Comment by LolandaE** [comment]
Message from Uelun:
The issue was re-opened as the issue (attachment only loading after multiple refresh) still persists. The fix is better than it was, but it is not completely fixed (it isn’t showing the error message and there are fewer refresh attempts). But users are still having difficulty loading the documents 50% of the time.
