### ISSUE TITLE
Investigate if Certbot renewal is automated for GWELLS

### ISSUE THREAD

**Issue by LolandaE** [bcgov/gwells#1827]
**As a** *Service Owner* **I want** *automated certificate renewals* **So That** *our digital service doesn't display "your connection is not private" messaging*

**Additional Context**
- Example from Wildfire team:
https://github.com/bcgov/wps/tree/main/openshift/certbot

The cert expired in March and magically renewed (at a later date). Prevailing theory is that Certbot is automated. but for the wrong date.

**Acceptance Criteria**
- [ ] Is Certbot automated for GWELLS?
- [ ] If Certbot is automated for GWELLS, does the renewal date align with the cert expiration?

**Comment by LocalNewsTV** [comment]
Certbot is deprecated
