### ISSUE TITLE
Fix GWELLS backend for local development

### ISSUE THREAD

**Issue by Christopher-walsh22** [bcgov/gwells#1868]
**Describe the task**
For Chris: Currently when running GWELLS locally the app is unable to edit or create records. When attempting to save the record you are given the error message "ERROR: SERVER ERROR". This issue needs to be resolved before local development for tasks relating to the backend can be resumed. 
For everyone else: Can edit Well and save, but cannot save records when attachment is added at the same time.
Possibly an issue with local instance of Minio

**Acceptance Criteria**
- [x] Chris is able to save edited or created Well records 
- [ ] All developers are able to save records when an attachment is added

**Additional context**
- This is not an issue when for users when testing in the live environment. On openshift Nginx will handle the proxy requests. 
- When running local the post requests are being made to :
"localhost:8080/api/8000/gwells/api/v2/submissions/staff_edit"

But to access the api the post will need to be directed to:
"localhost:8000/gwells/api/v2/submissions/staff_edit"

**Comment by LolandaE** [comment]
Chris only - cannot save record at all
Everyone else can edit well and save, but cannot save records when attachment is added at the same time.
Possibly an issue with local instance of Minio
