### ISSUE TITLE
BCeID Integration - GWELLS

### ISSUE THREAD

**Issue by LolandaE** [bcgov/gwells#1870]
**Describe the task**
Request BCeID integration for PROD. This will require contact with the SSO team to determine who request IDIM approval for PROD.

**Acceptance Criteria**
- [ ] Reach out to SSO team to request
- [ ] Request IDIM approval (if req'd by team)

**Additional context**
- How to make integration request: https://bcgov.github.io/sso-requests
- SSO Onboarding: https://github.com/bcgov/sso-keycloak/wiki/SSO-Onboarding

**Comment by norrisng-bc** [comment]
BCeID integration request has now been approved by the IDIM team, and the SSO team has enabled access to BCeID prod.

The IDIM team will provide an updated service agreement that needs to be signed, though that likely won't happen until April 2023 due to workload on their end.
