### ISSUE TITLE
Map Roles for Gold Keycloak Realm - GWELLS

### ISSUE THREAD

**Issue by LolandaE** [bcgov/gwells#1872]
**Describe the task**
To understand how realm roles and client roles are mapped in the current Keycloak and map out what they will look like in Keycloak Gold.

**Acceptance Criteria**
- [ ] We understand how the roles in GWELLS are mapped and how to configure the new Keycloak
- [ ] Confirm the plan for new configuration with SSO team

**Additional context**
- If there's no client roles, then we can use the exact same mapping for realm roles, but move them to client roles.
- Refer to #1863

**Comment by norrisng-bc** [comment]
Client-level roles aren't currently used in Silver, so we should be able to directly port the existing realm-level roles to client-level roles in Gold (done; see #1873), and use them in the same way.
