### ISSUE TITLE
Configure Roles in Gold Realm - GWELLS

### ISSUE THREAD

**Issue by LolandaE** [bcgov/gwells#1873]
**Describe the task**
Port roles to new test realm.

**Acceptance Criteria**
- [ ] Roles are ported to new Keycloak test realm as client roles
- [x] second
- [x] third

**Additional context**
- We expect to move from realm level roles to client level roles
- [CSS has an API available](https://github.com/bcgov/sso-keycloak/wiki/CSS-API-Account), could probably write a one-off script to do this, instead of doing so manually via the CSS dashboard
- [Differences between client/realm roles](https://github.com/bcgov/sso-keycloak/blob/dev/docs/migration-guide.md)

**Comment by norrisng-bc** [comment]
All 22 realm-level roles in Silver have been recreated in the Gold realm/integration as client roles.

Role groups and client-level roles do not appear to be used in the existing Silver realm.
