### ISSUE TITLE
preserve original comments when Alteration/decommission report is created

### ISSUE THREAD

**Issue by jakemorr** [bcgov/gwells#1889]
**As a** *water officer* **I want** *the original comments on a well record to remain when an alteration report or decommission report is created * **So That** *when I am working on a ground water license application, there is comments related to this that are erased*

**Additional Context**
- when the new report is created it replaces the old comments, we want these old comments to persist

**Acceptance Criteria**
- [ ] Given a well record has an alteration report submitted, When the alteration report is created with comments, Then the user can still access and see the original comments on the original well record
- [ ] Given a well record has an decommission report submitted, When the decommission report is created with comments, Then the user can still access and see the original comments on the original well record

**Comment by VitalJeevanjot** [comment]
Hi @jakemorr ,

I am trying to work on it, Can you please confirm if you are you talking about this "comments" field (below images are of same field from API and Frontend) :=

![image](https://user-images.githubusercontent.com/40867747/202711720-fe10a3e9-7b44-4494-bcb8-d9f19706eb8a.png)

or 
![image](https://user-images.githubusercontent.com/40867747/202711801-051ba5bb-984a-40f0-9788-cc1c9c935cab.png)
