### ISSUE TITLE
Pull Request Review for GWELLS Phase 1 (Alex)

### ISSUE THREAD

**Issue by jakemorr** [bcgov/gwells#1901]
**Describe the task**
Alex is doing some contracted work for GWELLS that will be split into PRs. those PRs will be attached here for our team to review and eventually deploy. 

**Purpose**
this ticket allows us to plan for reviewing the PRs in our sprint

**Acceptance Criteria**
-[ ] this ticket will be closed once all phase 1 PRs are deployed

**Additional context**
- there will be a ticket for Phase 2

**Comment by AlexZorkin** [comment]
Just testing out the permissions here.
