### ISSUE TITLE
GWELLS DB Export

### ISSUE THREAD

**Issue by jakemorr** [bcgov/gwells#1923]
**Describe the task**
Export of GWELLS data set to Excel 

**Purpose**
GWELLS Service Owner needs a pull of this Data, as the export function doesn't work on queries this large. 

**Acceptance Criteria**
- [ ] GWELLS SO has Export of Data

**Additional context**
- Fields Needed:
WTN
Company that did the work
Class of well
Created by
Created date
Construction start date
Alteration start date
Decommissioning start date 

Search filter:
Created date: 1 Jan 2022 to 31 December 2022 (inclusive) – all new records submitted in 2022

**Comment by norrisng-bc** [comment]
Export completed and emailed to GWELLS service owner.

**Comment by norrisng-bc** [comment]
Initial export missed wells that didn't have a drilling company. This has been fixed, and another export has been generated and sent to the service owner.
