### ISSUE TITLE
Update user access request guide

### ISSUE THREAD

**Issue by norrisng-bc** [bcgov/gwells#1953]
**Describe the task**
Create a replacement for the existing GWELLS user access request guide.

**Purpose**
The [existing user access request guide](https://apps.nrs.gov.bc.ca/int/confluence/display/WAT/GWELLS+user+access+request+guide?) is meant for the Silver custom realm, so it's no longer applicable to the Gold common realm.

**Acceptance Criteria**
- [ ] We have edit access to the Confluence space for GWELLS
- [ ] Service owner has an updated user access request guide to refer to

**Additional context**
- The replacement guide will likely have to be placed on Confluence as well, as the existing one documents the service owner's own internal processes.
- We'll therefore need edit access to the Confluence space as well

**Comment by LolandaE** [comment]
@norrisng-bc - Do you have any notes for this before you leave?

**Comment by LolandaE** [comment]
GWELLS user access request guide stored in GWELLS Teams Channel
