### ISSUE TITLE
Data Field Available in GWELLS API

### ISSUE THREAD

**Issue by LolandaE** [bcgov/gwells#1969]
**Describe the task**
Ensure new data field is available in GWELLS API called by DataBC

**Purpose**
The reason why this task is needed and/or what value it adds.

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
My knowledge on this is limited….so apologies if the wording is unclear.
Related old tickets that might help:
[WATER-1049 DataBC upload V2 GeoJSON files](https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-1049)
[WATER-833 Update wells_list GeoJson API](https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-833)

- Data is coming from GWELLS SO and going to DataBC (#1970)

Questions:
1. If DataBC is calling GWELLS API for this data, where is the data coming from in the first place? Is this a circular relationship? 
- A: Not circular, it will be going one way

2. What are the specific URLs for GWELLS API 
- **ACTION: Service Owner to provide**

3. Q for DataBC: What exactly do you expect in API response? (eg. structure, attribute names, etc.)

**Comment by jakemorr** [comment]
Follow up with SO Week of July 24, 2023
