### ISSUE TITLE
One-Time Bulk Database Update - GWELLS

### ISSUE THREAD

**Issue by LolandaE** [bcgov/gwells#1970]
**Describe the task**
~500 wells need the **Drinking Water Area Indicator** flag changed to YES right away.

**Purpose**
To update the well database to include **Drinking Water Area Indicator** flag state.

**Acceptance Criteria**
- [ ] Given the user is on the Well Summary page,  When they look up one of the WTN from bulk update, Then they will see **Drinking Water Area Indicator** marked as Yes. 

**Additional context**
- Going forward all other would be entered manually one at a time, using the tool set up in 2. (ticket #1967)
- The rest will default to NO
- File is in GWELLS Channel > Files > Existing Capture Zones in GWELLS

**Comment by davidclaveau** [comment]
Created the script for the well updates to mark the drinking_water_protection_area_ind attributes as `true`, but running the script makes the Well Edit page trigger the pop up on load, for example:

https://gwells-dev-pr-1996.apps.silver.devops.gov.bc.ca/gwells/submissions/100123/edit

I believe this is a rounding error in the `updateDegrees` function and the modal pop up conditional. Probably just need to identify the best way to round the decimals without losing precision for the check. [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWNxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e1dbc864ef15f28ccd06985c5ef73f7961028e46/Screenshot%202023-08-22%20at%205.41.27%20PM.png)

**Comment by davidclaveau** [comment]
Resolved the rounding error and updated the unit tests to accommodate the changes. Everything looks to be working in DEV as expected. Will need to change email recipient to SO when pushing to staging/prod (currently sending to Chris for testing purposes).
