### ISSUE TITLE
Data Validation - GWELLS

### ISSUE THREAD

**Issue by LolandaE** [bcgov/gwells#1971]
**Describe the task**
Build in 2-stage data validation for the new “Drinking Water Area Indicator” flag.

If “Drinking Water Area Indicator” is set to yes, AND a user tries to change the GPS coordinates (on well edit page) - a warning will pop up when the user goes to save the GPS coordinate changes saying something like “WARNING, this drinking water capture zone is delineated based on these GPS coordinate, do you need to change the coordinates? Y/N ---

If no. they need to cancel their changes and it won't let them save without see thing that message (disables save button)

If yes 2 things happen, they:
(1) can hit save (enables the save button), and 
(2) it automatically triggers a warning email to Gwells@gov.bc.ca that a capture zone delineated well has had its coordinates changed.

**Purpose**
It's imperative this field is kept up to date accurately, as a cascade of decisions will be made off this dataset.
See example warning and buttons that trigger actions on screen shot below – red boxes are suggested changes.

**Acceptance Criteria**
- [x] Given a user is on the Well Edit page accessing a record where the Drinking Water Area Indicator is set to yes, When they try to change the GPS coordinates and warning message will be appear and Then they will choose Yes or No.

- [x] Given a user is on the Well Edit page accessing a record where the Drinking Water Area Indicator is set to yes and tries to change the GPS coordinates, When the warning message appears and they select No, Then this will cancel their changes without saving.

- [x] Given a user is on the Well Edit page accessing a record where the Drinking Water Area Indicator is set to yes and tries to change the GPS coordinates, When the warning message appears and they select Yes, Then they can hit save and this will trigger a warning email to GWELLS staff (Emi) that capture zone delineated well has had its coordinates changed.

**Additional context**
- Need to notify GWELLS if there's a change. Warn users they need to ask.
- Will YES generate an overwhelming amount of emails? The hope is that it won't and the warning would be enough.
- Service Owner is flexible to a better way to accomplish this.

![image.png](https://images.zenhubusercontent.com/624f2ed04f19a502bdf062d9/ae301cfd-9793-4586-bf1c-7c34d3927b44)

**Comment by LolandaE** [comment]
Jake thinks we may need to pull in a UX resource to look at this ticket

**Comment by davidclaveau** [comment]
Made a few fixes to the modal so it reliably shows when drinking_water is true, and doesn't repeatedly pop up if the user has selected "Yes" to updating the coordinates (until they reload the page). Next step would be to ensure this modal appears if the other longitude/latitude or UTM Easting/Northing inputs are changed, and if the old coordinates appear if "No" is selected/ 

New issue is that if drinking_water is `true` on page load, and you change the coords and save, it will set the drinking_water back to `false` on next reload. Requires some debugging.

**Comment by Christopher-walsh22** [comment]
I have set up a call to a new api endpoint for one the modal has been accepted (and closed) and the user tries to submit the alteration. While implementing the logic to send the email notification to the GWELLS team I have learned that this will not be possible to simply send through the sustainment team outlook account. 

Starting the research on what setting up CHES [https://bcgov.github.io/common-service-showcase/services/ches.html] would entail.

**Comment by sanjaytkbabu** [comment]
Email SMTP: https://stackoverflow.developer.gov.bc.ca/questions/233

**Comment by davidclaveau** [comment]
Sanjay and I squashed the bugs with the prompt and reseting the coordinates if a user selects "No" (in the long/lat, as well as UTM and DMS inputs). Fixed the issue with the unit tests comparing to an old snapshot without drinking water toggle, and fixed the "uuid-ossp" extension in the migrations when being deployed to Dev.

**Comment by davidclaveau** [comment]
Looks like we were able to implement the [Common Hosted Email Service](https://digital.gov.bc.ca/bcgov-common-components/common-hosted-email-service/) into the drinking water update, but we're just awaiting approval from API Services. May need to [follow up with their team on RocketChat](https://chat.developer.gov.bc.ca/channel/aps-ops/thread/tSSkwgDSwawTZ4EHg) if the approval take much longer than a day or two (WALLY CDOGS was instant approval).

Should be pretty straightforward to implement once we're approved. [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc1FiIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b90e01c4eb93ce41ef46da0b5d71b5699c9bb73d/Screenshot%202023-08-18%20at%201.54.43%20PM.png)

**Comment by Christopher-walsh22** [comment]
After discussion with team I also investigated the possibility using the gov.bc.ca smtp service. This worked out in the end. If we want to continue down the path of using CHES in the future it doesnt seem difficult once our account would be set up. Currently smtp is functioning as needed, sending a minimalist email to specified inbox. In dev it is currently set to my own inbox. The email is a basic notification that just sends the well tag number and a short message. 


[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ0FqIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9f9eaa659dcbb219c6fbc1eb224a6e833ea82718/Screenshot%202023-08-21%20at%204.49.13%20PM.png)

**Comment by Christopher-walsh22** [comment]
I have updated the senders email address to be that of the Sustainment team. 
Slightly changed the wording of the message.

**Comment by davidclaveau** [comment]
Updated the email to include well # in subject heading, as well as the new and previous coordinates in the body so GWELLS user can make note of the changes. Also added some logic that notes when changes are made in local/dev/test environments vs prod.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcng3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--68112da10c2d9e5902262fecdeb55a11f62dc8d5/Screenshot%202023-09-07%20at%201.26.00%20PM.png)
