### ISSUE TITLE
Map out where and how attachments are stored

### ISSUE THREAD

**Issue by jakemorr** [bcgov/gwells#1973]
**Describe the task**
Service Owner would like us to map out how attachments are stored for GWELLS. Look at existing well attachments and is there a consistent identifying variable/factor that we can use to discern the document type and rename/re-date the document.

**Purpose**
Attachments in GWELLS are not searchable right now, we want to determine the best path forward for flagging/tagging well records with what type of attachment they have with the intent of making them searchable; knowing how attachments are stored from upload to storing the attachment, to removing the attachment. Ideally these flags/tags are automated so the data quality is improved for GWELLS. This Ticket is to understand an attachment's journey and determine the best course of action for the tagging of well records.

The desired approach would be to make the user tag the well record when the attachment is uploaded with the appropriate tag and GWELLS would then rename the file to match so the tag could be removed automatically if the attachment is removed.

GWELLS already has the functionality to change file names of uploaded attachments.

**Acceptance Criteria**
- [x] Understand how GWELLS stores attachments
- [x] Will the attachment storage methods for GWELLS need to be replaced in the near future
- [x] Understand the differences in this process for attachments on Public records vs Private records.
- [x] Create a visualization of how attachments are stored and accessed by GWELLS 
- [x] Create a visualization of how the attachments are connected to the well record and the proposed well record tags
- [x] Update #2010 with proposed solution to Attachments Issue

**Additional context**
- Recap of what needs to be displayed on the diagram after receiving draft.
- How GWELLS uses Amazon S3 buckets is different from the new government standard of practice. Not a compliance issue, but should be noted.
- GWELLS PIAs are stored in [Team's files](https://bcgov.sharepoint.com/:f:/r/teams/05196-GWELLS/Shared%20Documents/GWELLS/GWELLS%20PIAs?csf=1&web=1&e=wce8qu) for reference

Here is the export for searching back end for well records with attachments:
Vars:
private documents:
export WATER_1651_GWELLS_URL_PREFIX=https://apps.nrs.gov.bc.ca/gwells/well/
export WATER_1651_GWELLS_S3_PREFIX=https://gwells-docs-production.apps.silver.devops.gov.bc.ca/
export S3_HOST=gwells-docs-production.apps.silver.devops.gov.bc.ca
export S3_PUBLIC_ACCESS_KEY=<redacted> #In openshift, MINIO_ACCESS_KEY
export S3_PUBLIC_SECRET_KEY=<redacted> #In openshift, MINIO_SECRET_KEY
export S3_WELL_BUCKET=gwells-private

public documents:
export WATER_1651_GWELLS_URL_PREFIX=https://apps.nrs.gov.bc.ca/gwells/well/
export WATER_1651_GWELLS_S3_PREFIX=https://s3.ca-central-1.amazonaws.com/
export S3_HOST=s3.ca-central-1.amazonaws.com
export S3_PUBLIC_ACCESS_KEY=<redacted> #In openshift, S3_PUBLIC_ACCESS_KEY
export S3_PUBLIC_SECRET_KEY=<redacted> #In openshift, S3_PUBLIC_SECRET_KEY
export S3_WELL_BUCKET=gwells-docs

**Comment by LocalNewsTV** [comment]
Diagrams, Notes, and proposed solutions available on the GWELLS Wiki 
https://github.com/bcgov/gwells/wiki/Storage-of-Related-Documents

**Comment by LocalNewsTV** [comment]
2010 is a non-issue since documents are loading and stored in an appropriate manner.
