### ISSUE TITLE
Missing Fields from Well Summary/Edit Page

### ISSUE THREAD

**Issue by jakemorr** [bcgov/gwells#1995]
Aquifer ID and Aquifer Lithology Code missing from GWELLS Well Summary/Edit page

**Additional Context**
- these 2 fields were deleted in the most recent Contractor PR that was deployed. so they previously existed in GWELLS on the Well Summary/Edit pages. if we think it is easier, we can revert the changes to Prod and modify the PR to leave those fields in. 

- Aquifer Lithology code drop down:
    - Bedrock
    - Unconsolidated
    - Unknown
- Aquifer ID Select from Aquifer numbers that exist in the DB (Field was called Aquifer_ID)

**Acceptance Criteria**
- [x] Given I am on the Well Edit Page, When I enter Aquifer Lithology Code , Then I can select from a dropdown
- [x] Given Well Edit Page, When I go to Enter the Aquifer ID, Then the Well is connected to the aquifer through this number.
- [ ] Given I am on the Well Summary Page, When I Review the Page , Then Both Aquifer Lithology Code and Aquifer ID are visible
- [x] Given I am on the Well Summary Page, When I click on the Aquifer ID , Then I am brought to the Aquifer's Summary Page

**Comment by davidclaveau** [comment]
After meeting with SO, the Acceptance Criteria of _Given I am on the Well Summary Page, When I Review the Page , Then Both Aquifer Lithology Code and Aquifer ID are visible_ was deemed not needed and only the Aquifer ID is required to be visible on the Well Summary page.
