### ISSUE TITLE
Review GWELLS GitHub Repos

### ISSUE THREAD

**Issue by LolandaE** [bcgov/gwells#2003]
**Describe the task**
Devs to review these GitHub repos:
https://github.com/bcgov/GWELLS-QAQC_Geocode_ArchiveData
https://github.com/bcgov/GWELLS-QAQC_Docker
https://github.com/bcgov/GWELLS-QAQC-RShiny-Dashboard

**Purpose**
To determine how feasible it would be to incorporate them into GWELLS dashboard:
https://bcgov-env.shinyapps.io/gwells-qaqc-rshiny-dashboard/

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by LocalNewsTV** [comment]
Work was assigned to a `code with us` [#2074](https://github.com/orgs/bcgov/projects/145/views/1?pane=issue&itemId=51311427)
