### ISSUE TITLE
Resolve Document Storage Issues

### ISSUE THREAD

**Issue by LolandaE** [bcgov/gwells#2010]
**Describe the task**
Resolve any document storage issues. This ticket will be filled out as a part of 1973.

**Purpose**
This will only be required if there were any issues were found in #1973. 

**Acceptance Criteria**
- [ ] Resolve storage issue 1
- [ ] Resolve storage issue 2

**Additional context**
N/A

**Comment by LocalNewsTV** [comment]
#2010 is a Non-issue and needs no further investigation after #1973 was completed
