### ISSUE TITLE
Create New UI for Uploading Documents - Select Document Type Feature

### ISSUE THREAD

**Issue by LolandaE** [bcgov/gwells#2011]
**As a** *GWELLS user* **I want** *to choose a document type when I upload a document* **So That** *the appropriate label is added to the record*.

WORKFLOW: 
- When uploading a document in GWELLS, the user chooses a document type. 
- The document type informs the label applied to the well tag and is used to rename the document to a specific naming convention.
- Multiple documents of the same time will have a number applied to the end of the name.

**Additional Context**
**ACTION**: Need all available documents that can be attached to Well Tags from Service Owner, this will be used for the label solution

**Acceptance Criteria**
- [x]  In GWELLS backend, create backend flags for a Well Tag to signal that it has a document attached of a specific type (add Labels on Well Tags)
- [x] Given I am on a Well Record, When I add an attachment, Then I can choose a Record Type

**Comment by QSu-2023** [comment]
[Uploading... GWELLS_Document Upload Naming Conventions and Guidelines.pdf]

**Comment by LocalNewsTV** [comment]
Blocked until more concrete list of File type options are given
