### ISSUE TITLE
Create UI for Deleting Documents from a Well

### ISSUE THREAD

**Issue by LolandaE** [bcgov/gwells#2012]
**As a** *GWELLS user* **I want** *to remove an attachment from a well* **so that** *I am confident the well tag labels in the well tag reflect the removal of that attachment*.

**Additional Context**
- Label is only removed when a type of record stored = zero 

**Acceptance Criteria**
- [ ] Given I am a GWELLS user, When I remove an attachment from a well, Then the well tag labels reflect the removal of that attachment

**Comment by LocalNewsTV** [comment]
Closed as duplicate
