### ISSUE TITLE
Enhance Automated Naming of Documents

### ISSUE THREAD

**Issue by LolandaE** [bcgov/gwells#2013]
**As a** *GWELLS user when I add an attachment to a well tag* **I want** *the names to be consistent* **So That** *they are easy to look up*.

**Additional Context**
- Enhance automated naming of documents based on document type. 
- This feature is already in place, just need to fully change the name of the document to: **Well Tag #-Document Type-Document Upload Date <which date and format to be confirmed>** (e.g. Well Tag #12345-Well Record-date format to be confirmed) 
- Right now it just modifies the existing document name to add the Well Tag number to the end.
- If multiple documents of the same type are added, add +1 number to the end (e.g. Well Tag #12345 - Well Record - 2)

**Acceptance Criteria**
- [x] Given I am a GWELLS user, When I search for a well tag number, Then all documents attached to that well tag will be displayed with a consistent naming convention
- [x] Given I am a GWELLS user, When I search for a well tag number with multiple documents of the same type attached, Then all documents attached to that well tag will be displayed with a consistent naming convention with incremental numbers

**ACTION: SO to confirm what the preference is: date related well action was performed vs the date document was uploaded.  upload date consistent and accurate, date well action was performed more valuable but increased chance of user error**

**Comment by QSu-2023** [comment]
The preference is to use the date related to well action was performed (users can choose the date from a calendar). Thanks!
