### ISSUE TITLE
first pass at applying labels to existing records

### ISSUE THREAD

**Issue by jakemorr** [bcgov/gwells#2026]
** as best as we can apply labels to existing well tags with attachments based on attachment names. This would be a bulk change, and there would be many existing records that do not have labels applied and need to be applied manually. 

following both a bulk change based on existing well tag attachment file names and the manual updates of the labels by GWELLS Administrators, the file names of the attachments should be updated to match the new naming convention - SEPARATE TICKET

**Purpose**
The reason why this task is needed and/or what value it adds.

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by LocalNewsTV** [comment]
Blocked until completion of #2063 due to existing files not adhering to any naming conventions

**Comment by LocalNewsTV** [comment]
Functionality works in Test as expected, will need to move to promote test -> prod to complete the ticket
