### ISSUE TITLE
Display licence number for licenced wells and link to Well licence

### ISSUE THREAD

**Issue by QSu-2023** [bcgov/gwells#2048]
**As a** *user* **I want** *licence number displayed for licenced wells* **So That** *I can view licence number and have access to the licence document by clicking on it. 

**Additional Context**
Refer to 2023_GWELLS_Aquifer_Dashboard_Enhancement document in GWELLS Teams Channel for additional details with screenshots.
- example of well that is licensed with no licence number: https://apps.nrs.gov.bc.ca/gwells/well/117131

**Acceptance Criteria**
- [x] Given I am on the Well Summary page for a licence wells (licence status = licenced), When I go to Licensing Information section, Then I can see licence number displayed.
- [x] Given I am on the Well Summary page for a licence wells, When I click the licence number, Then I will be directed to the licence documents page.

**Comment by QSu-2023** [comment]
I just confirmed with Leia that it is actually a bug fix for displaying licence number for a licensable well in Well Summary page.  Hope this helps.

**Comment by LocalNewsTV** [comment]
Bug found to not be an issue with the gwells repository, but an outside source.
