### ISSUE TITLE
Add a hyperlink to the tool tip description of Aquifer notations on Aquifer Summary page

### ISSUE THREAD

**Issue by QSu-2023** [bcgov/gwells#2049]
**As a** *user* **I want** *a hyperlink added "For details, click [here](https://www2.gov.bc.ca/gov/content/environment/air-land-water/water/water-licensing-rights/water-allocation-notations)" at the end of the tool tip description of Aquifer Notations * **So That** the Water Allocation Notations website is opened when I click "here"**

**Additional Context**
- Refer to 2023_GWELLS_Aquifer_Dashboard_Enhancement document in GWELLS Teams Channel for screenshots

**Acceptance Criteria**
- [ ] Given I am on Aquifer Summary page under Knowledge Indicators section, When my cursor hovers over the questions mark by Aquifer notations and the tooltip description shows up , Then I can see "For details, click [here](https://www2.gov.bc.ca/gov/content/environment/air-land-water/water/water-licensing-rights/water-allocation-notations)" is included in the description. When I click "here", it opens the website: https://www2.gov.bc.ca/gov/content/environment/air-land-water/water/water-licensing-rights/water-allocation-notations

**Comment by sanjaytkbabu** [comment]
Deployed to prod
