### ISSUE TITLE
Update GWELLS API for pumping test and aquifer parameters

### ISSUE THREAD

**Issue by QSu-2023** [bcgov/gwells#2050]
**Describe the task**
GWELLS API needs to be updated with adding a new end point for pumping test and aquifer parameters. 
The aquifer parameters (STORATIVITY , TRANSMISSIVITY,  HYDRAULIC_CONDUCTIVITY) can be removed from the existing endpoint of wells.

**Purpose**
Once the new end point/URL is ready, DataBC can pull data so that the dataset/spatial layer is available for users.

**Additional context**
- Aquifer Dashboard Team have finalized the fields need to be included for this new dataset before the endpoint is created. 
- if needed, refer to the uploaded file in GWELLS Teams: "2023_GWELLS Aquifer Dashboard Enhancement for Tickets"
- List of the fields:
GW_WWL_SYSID
WELL_TAG_NUMBER
IDENTIFICATION_PLATE_NUMBER
WELL_STATUS
LICENCE_STATUS
WELL_DETAILS_URL
FINISHED_WELL_DEPTH
BEDROCK_DEPTH
**start_date_pumping_test
pumping_test_description
test_duration
boundary_effect
analysis_method
STORATIVITY
TRANSMISSIVITY
HYDRAULIC_CONDUCTIVITY
specific_yield
specific_capacity
comments**
AQUIFER_ID
Aquifer subtype
Aquifer material
GEOMETRY
OBJECTID
SE_ANNO_CAD_DATA

Note:
- There is a ticket about sig fig changing(Ticket #2079 Reduce sig figs for aquifer parameters etc.). 
- Will need to verify the Data Type and Data Precision for DataBC:

![image](https://github.com/bcgov/gwells/assets/62873746/f4c61311-81f0-4111-87af-b8690c82c5c2)

**Comment by QSu-2023** [comment]
Talked with Leia, she is not quite sure about the rational why we have to create a new API other than adding these fields to the existing GWELLS API but she pointed out one possible reason: Pumping test and aquifer parameters data contains multiple lines/tests of information for each well. This is similar with Lithology which is in separate table in the database and has it's own API for DataBC.

I will ask Geomatics team and DataBC if we can have further discussion/meeting on this.

**Comment by QSu-2023** [comment]
Confirmed with DataBC that a new endpoint/URL will be needed, just like what they have for wells (https://apps.nrs.gov.bc.ca/gwells/api/v2/gis/wells?realtime=true) and lithology (https://apps.nrs.gov.bc.ca/gwells/api/v1/gis/lithology), etc.  I will now discuss with the Aquifer Dashboard Team to finalize the fields need to be included in this new dataset.

**Comment by acatchpole** [comment]
Data for aquifer parameters is found in 2 tables:
 - Legacy : well
 - New : aquifer_parameters

Need to confirm with SO if Legacy data needs to be included.

**Comment by LocalNewsTV** [comment]
OBJECTID
SE_ANNO_CAD_DATA
GW_WWL_SYSID

These columns are not needed in the export, and are not part of any other export gwells is carrying
