### ISSUE TITLE
Add "Aquifer Parameters" filter on the map on Aquifer Summary page and Aquifer Search Page

### ISSUE THREAD

**Issue by QSu-2023** [bcgov/gwells#2051]
**As a** *Hydrogeologist* **I want** *the Pumping Test and Aquifer parameters layer to be added on the map on Aquifer Summary page and Aquifer Search page* **So That** *"I can choose to view only the wells with data input in the Pumping Test and Aquifer Parameters table*

**Additional Context**
- In the upper right box within the map, add the ability to select “Aquifer Parameters” with a check box, in order to be able to toggle on/off which wells have this information. 
- Put this option above “observation wells” 
- Do this on both the Aquifer Summary and Aquifer Search page  
- One checkbox with only 1 halo color for “Aquifer Parameters” 
- Criteria: if there is any data input in the Pumping test and Aquifer Parameters table, not limited to aquifer parameters only.  

Also remove “wells – aquifer parameters” from the legend. (can be in separate ticket if needed)

Refer to 2023_GWELLS_Aquifer_Dashboard_Enhancement document in GWELLS Teams Channel for screenshot

**Acceptance Criteria**
- [ ] Given I am on the Aquifer Summary/Search page, When I check/uncheck the checkbox of  "Aquifer parameters", Then the aquifer parameters data (wells with any data input in the Pumping Test and Aquifer Parameters) will be reflected on the map.

**Comment by acatchpole** [comment]
deployed to prod
