### ISSUE TITLE
Make wells with hydraulic property more visible in Aquifer Summary page

### ISSUE THREAD

**Issue by QSu-2023** [bcgov/gwells#2053]
**As a** *user* **I want** *halo color changed (to green or other colors) for wells with hydraulic property* **So That** *I can view these wells easily in the map on the Aquifer Summary page*

**Additional Context**
- Refer to 2023_GWELLS_Aquifer_Dashboard_Enhancement document in GWELLS Teams Channel for screenshots
- this is just changing the halo color

**Acceptance Criteria**
- [ ] Given I am on Aquifer Summary page, When I check Wells layer, Then I can see "Wells- aquifer parameters" easily

**Comment by sanjaytkbabu** [comment]
<img width="1435" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDl0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d9356b3049024198c1da2d57ae6fa3432b4a9f17/image.png" alt="image.png" />

**Comment by sanjaytkbabu** [comment]
Aquifer parameters has been added to an existing well in Gwells Staging database.

**Comment by sanjaytkbabu** [comment]
Approved by Su. Will be deployed along with 2052.
