### ISSUE TITLE
R Shiny Dashboard integration into GWELLS

### ISSUE THREAD

**Issue by LolandaE** [bcgov/gwells#2074]
**As a** *Groundwater Data Specialist* **I want** *selected R Shiny Dashboard capabilities integrated into GWELLS* **So That** *real-time changes (other than 24 hours) and access to additional (non-public) info in the database are allowed*

- [ ] Create a new “QA/QC Dashboard” menu in GWELLS for the integration.
- [ ]  Make this “QA/QC Dashboard” for approved internal users only.
- [ ]  Only the following tabs need to be migrated/enhanced or created to GWELLS: Tab Table.JPG
- [ ] Change the data source from pre-downloaded public viewable data (CSV) to the Province’s groundwater well database (PostgreSQL).
- [ ] Discard/Ignore the features of “Date Added Range”, “Well Tag Number Range”, “Download QA/QC Table” and “Download Drillers Table” for the migration.
Each tab under QA/QC Dashboard in GWELLS:
- [ ] 1. Each table will have its own specific search criteria.
- [ ] 2. Remove “Natural Resource Region” from the region names. For example: show “Omineca Natural Resource Region” as “Omineca”.
- [ ] 3. Filter of each column in each table can filter out or pick up blank/missing data.
- [ ] 4. Make Well Tag Numbers (“WTN”) linkable to the well records in GWELLS. For example, WTN 128671.
- [ ] 5. Add function of “Export search result” (in Excel or SCV)

**Additional Context**
- This work is being done under [Code With Us contract](https://marketplace.digital.gov.bc.ca/opportunities/code-with-us/7f978fd7-5b67-434b-be4d-878f20a80ee8)

**Comment by sanjaytkbabu** [comment]
PR review added: https://github.com/bcgov/gwells/pull/2097
