### ISSUE TITLE
Update sortable keys in filters.js

### ISSUE THREAD

**Issue by LocalNewsTV** [bcgov/gwells#2087]
**Describe the task**
Iterate through all the column types in in the gwells search results and find the ones that do and do not work

**Purpose**
by updating the sortable keys we can properly identify which columns work as intended, and which do not

**Acceptance Criteria**
- [ ] All fields are tested / updated accordingly

**Additional context**
- you can add a print statement in `WellListOrderingFiler.get_ordering()` to check if a field is valid. If it isn't it will default to `well_tag_number`

**Comment by fergmac** [comment]
<img width="1143" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTZjQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--46cc039a4f461992265d689bad7e3bbe712ca9e7/Screen%20Shot%202024-01-04%20at%208.45.35%20AM.png" alt="Screen Shot 2024-01-04 at 8.45.35 AM.png" />

**Comment by fergmac** [comment]
<img width="1360" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUdjQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dd06ece0a5547c121cd9a42c9965cc992c2e55e4/Screen%20Shot%202024-01-04%20at%208.34.13%20AM.png" alt="Screen Shot 2024-01-04 at 8.34.13 AM.png" />
