### ISSUE TITLE
Make more entries/fields mandatory for newly constructed wells

### ISSUE THREAD

**Issue by QSu-2023** [bcgov/gwells#2089]
On Submit Report/Well Activity Submission page, make the following fields mandatory (add * next to the field names & show error messages during submission, just like "Well class" and "intended water use" which are currently mandatory) 

if type of work is **construction** and start date of work is not earlier than 2016-03-01 (when this became mandatory in licensing a well)(validation only applies to this criteria):

- If Class of Wells is Dewatering/Drainage (and well subclass is permanent) or Water supply: Well Identification Plate Number, Where Identification Plate Attached
- Start Date of Work, End Date of Work
- Well Owner Name, Owner Mailing Address
- Geographic Coordinates (if possible/optional: error message for coordinates out of the province boundary)
- Drilling Method(s)
- Total Depth Drilled(?), Finished Well Depth, Final Casing Stick Up

**Comment by fergmac** [comment]
Duplicate of [issue 2112](https://github.com/bcgov/gwells/issues/2112)
