### ISSUE TITLE
Change "dugout" to "dug" in Drilling Method(s)

### ISSUE THREAD

**Issue by QSu-2023** [bcgov/gwells#2090]
Update Back end to replace all instances of Dugout with dug

-  Dugout is more like a pond and a dug well is not called dugout. The dropdown list of "Drilling Methods(s)" on Submit Report/Well Activity Submission page and Well Editing/Update Well Information page should be updated to replace "Dugout" with "Dug". 

- Accordingly, the dropdown list in the Advance Search and search result table should be also updated.

-  Also, all of the well records that include "Dugout" as Drilling methods should be updated to "Dug". 

Additional Context:
1. A few wells' Drilling Methods is Dugout AND Excavating. The Excavating needs to be kept/unchanged. 
2. There are only 89 wells based on my search. I can also manually update them if that is easier.

**Comment by acatchpole** [comment]
Deployed to prod, and command to update codes run. Working as intended.
