### ISSUE TITLE
Add address autocomplete feature to address fields' data entry

### ISSUE THREAD

**Issue by QSu-2023** [bcgov/gwells#2094]
**As a** *user* **I want** *the suggested address automatically populate while I enter an address to Owner Mailing Address and Street Address/Well Location Address on Well Editing page and Submit Report page* **So That** *it is easier to enter an address with less typo/errors*

**Additional Context**
- example of address autocomplete feature: [BC assessment](https://www.bcassessment.ca/ )
- we will want to see what other teams have done for this, as there are free and paid services to assist with this, the free ones may have a limit on how often they can be used.
- we have the freedom to implement this feature however we see fit to get the intended results

**Acceptance Criteria**
- [ ] Given that I am trying to enter an address to Owner Mailing Address or Street Address/Well Location Address on Well Editing page or Submit Report page, When started to type in street number or street name , Then the suggested address will pop out in a drop down list.

**Comment by fergmac** [comment]
I should have picked something up from coming soon, I believe there is some pre work associated with this ticket.

**Comment by sanjaytkbabu** [comment]
Decided to go with mapbox as we need addresses outside of BC.
docs: https://docs.mapbox.com/mapbox-search-js/guides/autofill/
pricing https://www.mapbox.com/pricing#autofillsession

**Comment by QSu-2023** [comment]
Probably just have this feature for BC address only?

**Comment by sanjaytkbabu** [comment]
Hey Su, sure we could do that only for BC addresses

**Comment by sanjaytkbabu** [comment]
API: https://geocoder.api.gov.bc.ca/addresses.json?minScore=50&maxResults=5&echo=false&brief=true&autoComplete=true&addressString=
usage: https://geocoder.api.gov.bc.ca/addresses.json?minScore=50&maxResults=5&echo=false&brief=true&autoComplete=true&addressString=mayfair

ref: https://www2.gov.bc.ca/gov/content/data/geographic-data-services/location-services/geocoder
https://bcgov.github.io/ols-devkit/examples/address_autocomplete.html

**Comment by sanjaytkbabu** [comment]
GEOCODER API added to openshift/ocp4/backend.dc.json and Config Map 
(26e83e-dev, test & prod -> Config Map -> gwells-global-config)

**Comment by sanjaytkbabu** [comment]
All PR suggestions have been implemented and is currently in Dev.

**Comment by acatchpole** [comment]
deployed to prod

**Comment by sanjaytkbabu** [comment]
deployed to dev

**Comment by acatchpole** [comment]
Deployed to prod (for reals this time)
