### ISSUE TITLE
research options for Address autocomplete features

### ISSUE THREAD

**Issue by jakemorr** [bcgov/gwells#2098]
**Problem Description** 
**In order to** add an address autocomplete to gwells, We **needs to** investigate the options on how we do this.

**Solution Needs**
- the need is for addresses to auto complete as they are typed into the Owner Mailing Address or Street Address/Well Location Address fields on Well Editing page or Submit Report page, i.e. how https://www.bcassessment.ca/ does this

**Timebox**
- How much effort are we committing to this research? 1 day of work (may span over a few to get response from other teams)

**Outcome**
Details describing the outcome of the research 
- Was it successful? do ticket #2094
- Was it unsuccessful? discuss with SO

**Additional Context**
- other teams likely use a similar feature we want to be sure to canvas the other teams at DDS for an answer before moving into a direction
-question for SO: how frequently do we anticipate this being used (determines whether we need a simple or robust service to support it)
-WALLY already has this feature, so we could possibly use the code from this.

**Comment by fergmac** [comment]
mapbox autofill:
- docs: https://docs.mapbox.com/mapbox-search-js/guides/autofill/
- pricing https://www.mapbox.com/pricing#autofillsession

**Comment by sanjaytkbabu** [comment]
API: https://geocoder.api.gov.bc.ca/addresses.json?minScore=50&maxResults=5&echo=false&brief=true&autoComplete=true&addressString=<searchString>
usage: https://geocoder.api.gov.bc.ca/addresses.json?minScore=50&maxResults=5&echo=false&brief=true&autoComplete=true&addressString=mayfair
