### ISSUE TITLE
Wells missing during Aquifer search

### ISSUE THREAD

**Issue by sanjaytkbabu** [bcgov/gwells#2102]
**Describe the Bug**
'Number of wells correlated to the aquifer' in Aquifer summary page doesn't match the number of wells displayed on the page when clicking on the well count hyperlink.

**Expected Behaviour**
'Number of wells correlated to the aquifer' in Aquifer summary page matches the number of wells displayed on the page when clicking on the well count hyperlink.

**Actual Behaviour**
'Number of wells correlated to the aquifer' in Aquifer summary page doesn't match the number of wells displayed on the page when clicking on the well count hyperlink.

** Steps To Reproduce**
Steps to reproduce the behaviour:
1. Go to Aquifer Search
2. Check 'Aquifer parameters' and hit search
3. Click on Aquifer #55 
4. Click the hyperlinked well count and cross check the count

<img width="1289" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXFkQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b121aa5dccf99d09137965f9a879d1aa87e50eb1/image.png" alt="image.png" />

<img width="1278" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMW1kQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1ddb339aaccbd9f9d36de9f2a0a798340057c629/image.png" alt="image.png" />

**Comment by LocalNewsTV** [comment]
Application works as intended. Bad data was present in the database and getting filtered out, causing a difference in numbers
