### ISSUE TITLE
Aquifer number reversion on Wells page

### ISSUE THREAD

**Issue by QSu-2023** [bcgov/gwells#2108]
**Describe the Bug**
It was first noticed by Leia Fougere by working on WTN 97148. After the adding some pumping test/aquifer parameters data and hit save, the aquifer number was reversed back to 217. (A bulk aquifer number change was completed on June 01, 2023 by Christine Bieber. WTN 97148 is one of the well that was changed from Aquifer 217 to  Aquifer 1248 during that bulk change.)

**Expected Behaviour**
After an editing of a well record and hit save, only the change made should be saved. Other unchanged content shouldn't be impacted.

**Actual Behaviour**
The aquifer number was automatically reversed back to the previous value from an well well editing/save. 

** Steps To Reproduce** (SCARED TO TRY ON OTHER WELLS IN PROD AND CAN'T REPRODUCE IN STAGING (MANUALLY CHANGED AQUIFER# FROM 217 TO 1248 FOR WTN 20138 IN STAGING AND SAVED, THEN MADE EDITING IN AQUIFER PARAMETERS AND SAVED, THE AUIFER NUMBER WAS NOT IMPACTED)
Steps to reproduce the behaviour:

Additional investigations are needed to figure out:
-  if this change was caused only from the editing of the Pumping Test and Aquifer Parameters section.
- which wells/fields are impacted (only the wells that were previously assigned to aquifer 217 ? only aquifer number field are impacted with wells with bulk change? etc. )

Note: 
Example of the wells that are impacted are: WTN 63134, 75532, 75533, 75534, 93840, 97148, 97589, 104459. 
It likely that any wells with the bulk aquifer change in June 01, 2023 by Christine Bieber was impacted with the further well editing (pumping test/aquifer parameters).

**Comment by sanjaytkbabu** [comment]
<img width="1119" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFRQQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e0af4e665b29715776d0b9e68f5a94c154e01432/image.png" alt="image.png" />
All the Wells currently having aquifer id 1248 has got an 'updated date' before the bulk change date June 01, 2023 indicating that the bulk change may not have gone through.

**Comment by sanjaytkbabu** [comment]
97148 well was updated to 1248, saved, then updated pumping test info and saved. The aquifer id was not reverted and we do not see any data loss during well edit.

**Comment by sanjaytkbabu** [comment]
[FC_WellAquifer_Correl_20230607.csv.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMi9QQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--062273e3bf1b18b48912488663414e75c2607a76/FC_WellAquifer_Correl_20230607.csv.zip)
The wells that were involved in bulk change in June 2023

**Comment by sanjaytkbabu** [comment]
Had a meeting with Su.
TODO: Find the list of wells that were updated after June

TODO for Su after list is provided
1. Perform Bulk change by Christian
2. Spot Check problem wells
3. Test reversion by updating pumping test description

**Comment by sanjaytkbabu** [comment]
[well_202401161215.csv.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHpQQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b29fd1b7b4026549d8ce88e18f3aa348a764b1fd/well_202401161215.csv.zip)
Wells updated after June 01 2023

**Comment by sanjaytkbabu** [comment]
[well_202401161223.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOW5QQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--917cdd8c0c4d1fc0198e6d61a20d78de2ec9f20c/well_202401161223.zip)

**Comment by sanjaytkbabu** [comment]
[wells-updated-after-batch-move.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFhRQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--10fb9d730a8d10124824f152df78990669815932/wells-updated-after-batch-move.zip)
Wells in FC_WellAquifer_Correl_20230607 list that were updated after June 01 2023 with old and new values

**Comment by sanjaytkbabu** [comment]
<img width="627" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzNvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d4807b0aaa3ab46104579828be97d58dabf5ff99/bulk_upload_roles.jpg" alt="bulk_upload_roles.jpg" />

Roles required for bulk upload permission

**Comment by sanjaytkbabu** [comment]
TODO:
Taking backup of affected records.
Christine to re-run the bulk update.

**Comment by sanjaytkbabu** [comment]
deployed to dev: https://gwells-dev-pr-2126.apps.silver.devops.gov.bc.ca/gwells/

**Comment by sanjaytkbabu** [comment]
This has been approved by Su to go to prod

**Comment by sanjaytkbabu** [comment]
deployed to prod
