### ISSUE TITLE
Data validation for well report submission 

### ISSUE THREAD

**Issue by QSu-2023** [bcgov/gwells#2112]
**As a** *GWELLS service owner* **I want** *to make more entries mandatory* **So That** *the well report submission (especially by drillers/BCeID users) will include the information required by the GWPR [Groundwater Protection Regulation](https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/39_2016) 

**Additional Context**
1. On Report Submission page, for construction/alteration/decommission report, make the following fields mandatory:
   - Well Owner Name & Owner Mailing Address mandatory 
   - GWPR requires the Name, Address, City, Province, and Postal code related to the owner of the well
   
2. For **NEW wells only** (well construction date "start of work" or "end of work" is on or after Jan 1st 2024), the following entries are mandatory for **Construction report submission**:
   - Start Date of Work & End Date of Work 
   - Well Identification Plate Number & Where Identification Plate Attached only if: 
      - Class of Well = water supply or 
      - class of well = recharge or injection, or 
      - class of well= dewatering, and subclass=permanent
   - Drilling Method(s)
   - Total Depth Drilled & Finished Well Depth
   
3. Add * for mandatory fields
   - Ensure Validation for NEW Wells only( wells constructed ("start of work" **or** "end of work") is on or after Jan 1st 2024).
   - Wells prior to that date only require:
      - Well Owner Name & Owner Mailing Address mandatory 
      - GWPR requires the Name, Address, City, Province, and Postal code related to the owner of the well

   
**Acceptance Criteria**
- [ ] Given a GWELLS user open a new construction/alteration/decommission report on the submission page, mandatory fields are marked with * .
- [ ] Given a GWELLS user filled the construction/alteration/decommission report on the submission page , When submit button is clicked, Then a warning message will show up for the mandatory fields that are missing data (or the fields are highlighted in red? with the warning message?).

**Comment by fergmac** [comment]
We are removing the following requirement from this task:

- class of well= dewatering, and subclass=permanent

We currently cannot differentiate between dewatering and drainage well classes and the value add currently is low.

[further context in related bug ticket](https://github.com/bcgov/gwells/issues/2130)
