### ISSUE TITLE
Force 1 of 3 well location information. 

### ISSUE THREAD

**Issue by QSu-2023** [bcgov/gwells#2113]
**Problem Description** 
**In order to** force 1 of the 3 well location information is filled for well report on Report Submersion page ), the service owner **needs to** developers help to discuss/investigate if there is a solution with appropriate/convenient/easy approach. If not, maybe leave as is. 

**Solution Needs**
- GWPR requires: “the property on which the well is located described by its site address, legal description or parcel identifier number (PID)”

**Timebox**
- How much effort are we committing to this research? not much, a quick discussion should be good

> Following details added based on conversation with SO 
- If user chooses to fill out legal description, they only need to enter a minimum 1 field in that section.
- `Description of Well Location` is not part of section 3 "Parcel Identifier"
## Acceptance Criteria
- [x] User **must**  fill out one of three Well Location sections (legal description, parcel Identifier, Well Location Address)
- [x] Highlight information stating one section must be filled out
- [x] Add Tooltips To the legal description section for further clarity

**Comment by LolandaE** [comment]
@QSu-2023
What qualifies as a 'legal description' for well location? 

We have a few options on how to do the validation:
1. only allow what's required by the GWPR (this would be the least work)
2. only allow what's required by GWPR and a 4th well location qualifier around 'rural area' situation described above
3. create a new workflow for if someone cannot provide what's required by GWPR (this would be the most work)

**Comment by LocalNewsTV** [comment]
Updated ticket with additional information for future reference
