### ISSUE TITLE
Changing history error and potential data loss with aquifer parameters table

### ISSUE THREAD

**Issue by QSu-2023** [bcgov/gwells#2122]
**Describe the Bug**
For a well with data (WTN 116467) in the aquifer parameters table, if I make any edit that does not necessarily related to the table, the change history will indicate this table was changed to none.  At this time, the table is still shown properly in the well summary page.  

Then if I go to to the well editing and make some changes of this table, the table is updated on the well summary change but nothing is shown in the change history. If I come back after a few days, this table is disappeared on the well summary page

**Expected Behaviour**
The change history can record the editing correctly. 
Also, any further editing of the well won't cause any data loss such as the pumping test and aquifer parameters table.

**Actual Behaviour**
Further well editing will eventually cause data loss of the pumping test and aquifer parameters table. 
The change history is recording deleting actions on the pumping test and aquifer parameters stable that was not performed by the user.

** Steps To Reproduce**
Steps to reproduce the behaviour:
1. Choose a well with data in the pumping test and aquifer parameters table in the well summary
2. Click on the "edit" button and make any editing (but not deleting the pumping test and aquifer parameters table) about the well then click the "save" button to save.
3. Scroll down to change history
4. The change history shows that the table was deleted too 
5. Go back to the well summary, the table is still there.  
6. Go to the editing page and make some changes of the table, and save. The change history can't record this change but the well summary displays the update properly
7. Go back to this well later (I checked a few days after), the table is totally gone in the well summary.

**Comment by sanjaytkbabu** [comment]
Message from Christine: After a bulk upload to update aquifer number for a well no history is shown for well that was previously uncorrelated.

<span><span class="ui-provider buw bux bpq buy buz bva bvb bvc bvd bve bvf bvg bvh bvi bvj bvk bvl bvm bvn bvo bvp bvq bvr bvs bvt bvu bvv bvw bvx bvy bvz bwa bwb bwc bwd" dir="ltr"><span><span style="font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, system-ui, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Web&quot;, sans-serif; font-size: 14px; white-space: pre-wrap;"><p style="margin: 0px;"></p><span><p>this is the change we made with bulk upload</p>
well_tag_number | aquifer_id
-- | --
100125 | 1901
117042 | 1901
20143 | 1901
100123 | 1901

<p>&nbsp;</p></span></span></span><span><span style="font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, system-ui, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Web&quot;, sans-serif; font-size: 14px; white-space: pre-wrap;"><p style="margin: 0px;"></p><span><p>it was 20143 that has no change history</p></span></span></span></span></span>

**Comment by acatchpole** [comment]
On any edit to the well, the existing row in aquifer_parameters table has it's WTN set to null. A new row with a new testing_number (primary key for the table) is generated with all other non-event fields being set identical to the original entry. 


![Image](https://github.com/bcgov/gwells/assets/113044739/4cc866a2-9ed9-4d4a-bbc2-86e0007e2bf4)

**Comment by acatchpole** [comment]
A band-aid fix has been pushed to prod. There is no data loss and an accurate change history.
BUT, there still exists an issue that needs to be addressed which is described in [this bug ticket.](https://github.com/bcgov/gwells/issues/2155)
