### ISSUE TITLE
Auditing Dependencies

### ISSUE THREAD

**Issue by LolandaE** [bcgov/gwells#2124]
**Describe the task**
Review the application dependencies for the frontend and backend. We want to get an idea of how out of date we are. If we are using and unsecure or unsupported versions.

- ie. unsupported Django version 2.2

**Purpose**
We can better understand how big of a lift it will be to get to supported version and ideally to the latest versions. Then we can investigate adding newer dependencies that provide a more modern development experience.

**Acceptance Criteria**
- [ ] Document the current state of frontend and backend dependencies.
- [ ] A plan created for tackling a first slice of backend dependency updates. Django 2.2 to Django 3. (#2189) 
- [ ] A plan created for tackling a first slice of frontend dependency updates. Vue 2.6.10 to Vue 3.4.19. (#2190)

**Additional context**
- Action item from Jan 9/24 retro

**Comment by fergmac** [comment]
- https://docs.djangoproject.com/en/2.2/howto/upgrade-version/
- https://docs.djangoproject.com/en/2.2/howto/upgrade-version/

**Comment by fergmac** [comment]
[GWELLS Dependencies.xlsx](https://github.com/bcgov/gwells/files/14543732/GWELLS.Dependencies.xlsx)
