### ISSUE TITLE
Expand Dummy Data in Dev Environment

### ISSUE THREAD

**Issue by LolandaE** [bcgov/gwells#2125]
**Describe the task**
Import data from PROD to DEV environment. Need to check what can be imported and ensure there is no sensitive data. Alternately expand dummy data that is currently in DEV. 

First option: Point local environment to get data from staging d/b. If this doesn't work, then next option is to create a new database for local that updates alongside prod and staging.

**Purpose**
Small dataset in local and dev environments made some testing hard

**Acceptance Criteria**
- [x] Given developer working in local environment, they have access to a complete dataset

**Additional context**
- Action from Jan 9 retro

**Comment by davidclaveau** [comment]
I was able to create a `TransportServerClaim` on GWELLS' staging namespace that exposes a port for the database for external connections. This setup is mostly used for cluster-to-cluster migrations, but works for our needs. More information on the build can be found here: https://developer.gov.bc.ca/docs/default/component/platform-developer-docs/docs/platform-architecture-reference/set-up-tcp-connectivity-on-private-cloud-openshift-platform/

Follow up: we might need to look into certain restrictions for this setup in the future, including but not limited to:
- cloning the staging database to create a pod for these local connections
- making these local connections "read-only" to ensure data isn't erroneously deleted
