### ISSUE TITLE
Well report submission failed

### ISSUE THREAD

**Issue by QSu-2023** [bcgov/gwells#2132]
**Describe the Bug**
I was trying to do a new well report submission, and at the final step of clicking the submit button, then after a banner pops up and I click the save button to confirm, nothing happens and I can't progress to the next screen, and the well is not entered in GWELLS

**Expected Behaviour**
After I click "preview and submit" button then "save" button, banners will show up on the right top "saving" then "well report submitted", then the page will refresh to the well summary of the newly created well (with WTN)

**Actual Behaviour**
Nothing happened after the "save" button was clicked: no banners, no page refreshing, no well record was created.

** Steps To Reproduce**
Steps to reproduce the behaviour:
1. Go to report submit page, fill in some data for a new well report 
2. Click on "preview and submit" button, then "save" button
3. Nothing happens

**Comment by acatchpole** [comment]
Fix tested by SO and deployed to prod
