### ISSUE TITLE
Rebuild Testing Suite - Part 1 - Backend

### ISSUE THREAD

**Issue by LolandaE** [bcgov/gwells#2140]
**Describe the task**
Bring the test suite to an 85% Coverage rate

**Purpose**
Since the test suite is in an unmanaged position, overall testing in the application has reduced to just over 74% total coverage.

**Acceptance Criteria**
- [ ] Test coverage rate > 85%

**Additional context**
- Backend uses [django.test](https://docs.djangoproject.com/en/5.0/topics/testing/)
- Backend tests can be run from terminal using make commands, reference the makefile for list
- Could disable all tests and run them locally, fix them over time and bring them online.
- Likely be a lot of broken tests due to how much code has changed and tests haven't been
- #2139 
- For detailed Testing writeup see the [Wiki](https://github.com/bcgov/gwells/wiki/Testing)

| Statements | Missed | Skipped | Percentage | 
| ---------- | ------ | ------- | ---------- | 
| 11,777     |   3054 | 0       | 74%        |

**Comment by davidclaveau** [comment]
Preliminary work completed on this branch: [gwells-2140-backend-tests](gwells-2140-backend-tests).

Added a few test suites for the `aquifers/change_history` file and partially completed tests for the `aquifers/serializers_v2` file for the class `AquiferDetailSerializerV2`.

Side notes for running tests:
You can run `/bin/bash -c "cd /app/backend/; python -m coverage run manage.py test aquifers --noinput"` from inside the Docker backend container to run just the aquifer tests.
