### ISSUE TITLE
API Tests - Part 3

### ISSUE THREAD

**Issue by LolandaE** [bcgov/gwells#2142]
***Describe the task**
Get the test suite up and running as is.

**Purpose**
Test suite is currently in a broken state. Get the core up and running and devs can use the unit test library to write test for PRs.

**Acceptance Criteria**
- [x] Dev can write tests developing locally

**Additional context**
- Likely can be run by Postman locally
- [Audit ticket ](https://github.com/orgs/bcgov/projects/145/views/1?pane=issue&itemId=52421527)

**Comment by LocalNewsTV** [comment]
The API is the Backend.
Duplicate ticket of #2140

**Comment by fergmac** [comment]
The following command will run the api tests locally:

You can use the --folder option to target a specific group within a test collection
`newman run ./tests/api-tests/wells_search_v2_api_tests.json --global-var base_url=$GWELLS_API_BASE_URL --folder "Search"`
