### ISSUE TITLE
Well report submission failure for SOME users

### ISSUE THREAD

**Issue by QSu-2023** [bcgov/gwells#2146]
**Describe the Bug**
I got a couple of bug report from external users/drillers that they couldn't submit well report successfully after they click "review and submit" button. I double checked with one of them and confirmed that he tried this morning and failed. He was able to log in, fill data, and click "review and submit" but nothing happened after.  His BCeID account is integrity99 (info@integritydrilling.ca). 

**Expected Behaviour**
In well report submission, after the review and submit button was clicked and confirmed, the page refreshes and a new WTN is created with the summary page open. 

**Actual Behaviour**
Nothing happed after the button was clicked. 

Note: 
I've talked to a driller I know, she tried this morning and it worked fine to her. 
I also tried in staging yesterday, it worked for me. 
I've checked with a couple of gov/IDIR staff, all worked with no issues this morning.

**Comment by LocalNewsTV** [comment]
Users Affected: 2.

Attempted to replicate bug by using 4 different browsers: 
- Chrome
- Fire Fox
- Fire Fox Developer
- Safari
could not replicate

Attempted to replicate bug by using 3 different devices:
- M1 Macbook
- Windows 11 Laptop
- Android smartphone
could not replicate.

Awaiting further information regarding bug. Current assumption is that users attempted to submit well before the solution for #2132 was deployed and users contacted SO at later date

**Comment by LocalNewsTV** [comment]
SO Followed up with one of two users, helped them resolve issue locally.
Followup with other user expected to take place soon
