### ISSUE TITLE
Seed the GWELLS Database for Testing

### ISSUE THREAD

**Issue by LolandaE** [bcgov/gwells#2160]
**Describe the task**
To get some useful (more robust) fake data populated into GWELLS locally. Use PROD data and sanitize it (remove identifiers).

**Purpose**
This will help developers in GWELLS testing.

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by LocalNewsTV** [comment]
This ticket is a duplicate of #2125
