### ISSUE TITLE
Migrate GWELLS pipeline tests to GitHub Actions

### ISSUE THREAD

**Issue by fergmac** [bcgov/gwells#2170]
**Describe the task**
Use GitHub actions to run GWELLS tests on GitHub PR events.

**Purpose**
This is pre-work associated with migrating the GWELLS pipeline to OpenShift. Once we have the test pipeline step out of Jenkins, we can move toward using the OpenShift GitHub webhook flow to build and deploy the app.

**Acceptance Criteria**
- [ ] Django unit tests workflow created and runs successfully on GitHub push events
- [ ] API test fixtures loaded and API tests workflow created and runs successfully on GitHub push events

**Additional context**
- Add any other context about the task here.

**Comment by LolandaE** [comment]
A new ticket will be written up to capture the work to be done here.
