### ISSUE TITLE
Summary/Statistics of GWELLS visit/use

### ISSUE THREAD

**Issue by QSu-2023** [bcgov/gwells#2186]
**Describe the task**
The team lead want to know if there is a way to find out how many people are using GWELLS, for example, how many visits daily, weekly, monthly, or yearly. For the signed in users, how many are from internal staff, drillers, consultant, etc. (I assume we can try tell based on the email address)

**Purpose**
To show how GWELLS is useful for internal staff and public users.

**Acceptance Criteria**
- [ ] Can we use Google Analytics?
- [ ] Is Google Analytics/Matomo set up?
- [ ] How much effort would it be to make these tools work?
- [ ] Is there an org level tool used now that is not listed here? 

**Additional context**
Background info from the previous SO/PO:
- [Google Analytics](https://apps.nrs.gov.bc.ca/int/confluence/pages/viewpage.action?pageId=53677814) was initially used but might have been moved off due to government privacy and security issues. 
- Based on a Jira ticket (https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-751), Google Analytics may still be available but needs to get the URL.
- As an alternative, the analytics were set up using Matomo, but not sure how far the team got.  Not sure what happened to the Matomo link: https://water-matomo.apps.silver.devops.gov.bc.ca/. Can we get it working again?

**Comment by LolandaE** [comment]
@QSu-2023 - How much of a priority is this work?

**Comment by QSu-2023** [comment]
> @QSu-2023 - How much of a priority is this work?
The timeline was not specified, no rush.
