### ISSUE TITLE
"Export search results" won't export internal data properly on the Well Search page

### ISSUE THREAD

**Issue by QSu-2023** [bcgov/gwells#2199]
**Describe the Bug**
On Well Search page, if I modify the search result table's columns using "Add/remove columns" button and include columns that are internal only (for example, "created by", "updated by", etc.), the search result table couldn't be exported properly (either failed to download or no data shown in these internal columns/fields in the downloaded excel/csv)

**Expected Behaviour**
When I click "export search result" button on the Well Summary page, the search result table is downloaded successfully even there are internal only columns.

**Actual Behaviour**
The search result table either fail be downloaded or no data shown under the internal columns in the downloaded excel/csv file.

** Steps To Reproduce**
Steps to reproduce the behaviour:
1. Go to Well Search page.
2. Click on the "search" button to view the search out table
3. Click "add/remove columns" and choose one or more internal only columns, such as "created by" or "updated by"(log in needed)
4. click "excel" or "csv" under Export search results
5. see error: the file either failed to be downloaded, or, the downloaded file has the proper column but no data in the internal only columns (for example, "created by" or "updated by")

**Comment by LocalNewsTV** [comment]
This wasn't really a bug, it was just never implemented with auth
