### ISSUE TITLE
Consider to have closed (well status=closure) wells a different color on Well Search page

### ISSUE THREAD

**Issue by QSu-2023** [bcgov/gwells#2211]
**As a** *user* **I want** *to have closed/decommissioned wells (status=closure or abandoned) a different color on the map of Well Search page * **So That** *to save time for reviewing records and easily give a better idea of the wells in operation in an area without having to open every well record to see the status* - suggestion from a regional GW Protection Officer. 

**Acceptance Criteria**
- [ ] Given I am looking at the Well Search page, When the wells have an **abandoned** or **closure** status, Then the colour of the well is different from other wells
- [ ] use coloured dots instead of halos
- [ ] New dot appears in Map legend with other dots

**Comment by LocalNewsTV** [comment]
Updated Acceptance Criteria to include adding new color to map Legend

**Comment by lunamoonmoon** [comment]
Talked with SO
- ensure well closed colour on load
-  smaller size
- show artesian halo for closed wells
