### ISSUE TITLE
Make "single page" rather than "multiple page" as default on the Well Report Submission page

### ISSUE THREAD

**Issue by QSu-2023** [bcgov/gwells#2218]
**Describe the Task**
To make the "submit report" page default to single page instead of multi-page.

**Acceptance Criteria**
- Given a user selects the `Submit Report` page, `Single Page` becomes the default page view

![Image](https://github.com/bcgov/gwells/assets/62873746/f914d494-dee7-4d5a-b0ac-2223fcbe8284)

**Additional Context**
As a service owner, I still kept receiving emails from users who has the report submission issue (no response after submission). 

The solution for this issue is either or both of the following:
- Based on the sustainment team's investigation, this is due to the cache issue as the users side and this issue can be solved by a hard refresh (Shift + Ctrl + R). I've sent out emails to the current users for this solution. 
- Some other users reported the hard refresh is not enough, they tried "single page" (top right corner of the well report submission page) and it turned out worked.

What is the value of using multi-page functionality? Feedback from one driller was that each section is separated.

**Comment by LocalNewsTV** [comment]
The `submission issue` listed in this bug has been resolved.
