### ISSUE TITLE
Submit Report page warnings update

### ISSUE THREAD

**Issue by fergmac** [bcgov/gwells#2263]
**Describe the task**

Update the CSS for the "All form fields marked with a trailing asterisk are mandatory fields." text. Bring in line with these examples from further down the page:
- "A minimum of one type of well location information is required below:"
- "The map pin can be placed manually, by clicking, or by dragging on the map. The GPS coordinates will be updated automatically."

**Purpose**
To flag to the user that the fields with trailing asterisk are mandatory.  

We want to make it clear for users as early in the flow as possible which fields are mandatory to potentially save them submitting and then dealing with resolving the failed validation on the required inputs. 

**Acceptance Criteria**
- [ ] When a user goes to the [Submit Report](https://gwells-staging.apps.silver.devops.gov.bc.ca/gwells/submissions) page, the "All form fields marked with a trailing asterisk are mandatory fields." has the `bg-warning` class applied.

**Additional context**
![Image](https://github.com/bcgov/gwells/assets/20193291/7b126bd3-c9f5-453d-917a-b20b17f5f4f3)

![Image](https://github.com/bcgov/gwells/assets/20193291/ecbbe624-c549-47ae-bbd6-43827163b4fb)

**Comment by acatchpole** [comment]
deployed to prod
