### ISSUE TITLE
Freeze the title bar on the Wells search results

### ISSUE THREAD

**Issue by jakemorr** [bcgov/gwells#2268]
**As a** *Hydrologist* **I want** *the wells search results column headers to be frozen* **So That** *when I scroll down i still can see which column is which*

**Additional Context**
- mentioned in sprint review

**Acceptance Criteria**
- [x] Given I have searched for Wells, When I scroll through the results, Then the column headers move with my scrolling

**Comment by dallascrichmond** [comment]
Added CSS class called sticky-header to <thead> element to resolve the issue.
