### ISSUE TITLE
Change the cadastral colour in the aquifer map so it is different from the aquifer color

### ISSUE THREAD

**Issue by QSu-2023** [bcgov/gwells#2270]
**As a** *User* **I want** * the color of the cadastral layer in the aquifer/well maps to be changed from orange to grey (**Hex # 686868**) * **So That** *the cadastral layer is not in the same color with the aquifers, and I can tell them apart easily when I am viewing the map*

**Additional Context**
- Currently the aquifer and cadastral colors are both in orange in the aquifer map on the aquifer search/summary page, which is hard to tell them apart sometimes.

**Acceptance Criteria**
- [ ] Given that I am on the aquifer search/summary page, When zoom in to the map extent till the cadastral layer is visible, Then I can see the cadastral layer is in grey instead of orange (the aquifer color).

**Comment by lunamoonmoon** [comment]
PR 2301 merged and deployed
