### ISSUE TITLE
Move Matomo Geolocation to PVC

### ISSUE THREAD

**Issue by sggerard** [bcgov/gwells#2303]
**Describe the task**
Ensure that Matomo Geolocation database is non volatile and will persist through a pod restart. Otherwise location tracking information will be lost.

**Acceptance Criteria**
- Dbip geolocation database file persists through a pod restart

**Additional context**
- See Wally's config for a working setup
- May be worth mounting the entire /var/www/html folder instead of just /config and /misc

**Comment by acatchpole** [comment]
The GWELLS Matomo pod had actually been redeployed several months ago, so all location data from Late May to now was just based on the users browser language.

Created non-volatile storage for the geolocation database in Matomo:
 1. Under 'Storage' -> PersistentVolumeClaims -> Click [Create Persistent Volume]
 2. Set the PersistentVolumeClaimName to desired (eg. 'matomo-misc')
 3. Set Size to 1 GiB (lots of room for the <200MB location database)
 4. Leave other settings default and click [Create]
 5. Go to DeploymentConfigs -> Matomo -> YAML tab
 6. Under ```spec: template: spec: volumes: ``` add 
   ```yaml 
- name: matomo-misc
     persistentVolumeClaim:
       claimName: matomo-misc 
```
 7. Under ```spec: template: spec: volumeMounts: ```  add 
```yaml
- name: matomo-misc
  mountPath: /var/www/html/misc
```
8. Click [Save] and a new build will be triggered
9. Once the Matomo pod is up and running, go to the Matomo web portal and login as admin
10. Go to Admin -> System -> Geolocation and scroll to the bottom of the page and click [Download Geolocation Database] (this option might not be present on some versions of Matomo. see [here](https://matomo.org/faq/how-to/setting-up-accurate-visitors-geolocation/) for alternate instructions)

If you need to update existing visitor data with accurate geolocation, go to the Matomo pod and access its terminal.
1. Run ```php ./console usercountry:attribute 2024-05-01,2024-08-19``` (this is for May 01 to Aug 18, 2024).
   - This gets the location values attached to visitor records in the logs
2. Run ```./console core:invalidate-report-data --dates=2024-05-01,2024-08-19```
   - This causes all the reports in this range to be recreated
