### ISSUE TITLE
Link EMA records to Mines

### ISSUE THREAD

**Issue by sggerard** [bcgov/gwells#2308]
**Describe the task**
Link records from EPD to mines using the AMS sourceID permit number. Kelly will provide a list of permits for each mine that we can use to build a lookup table.

**Purpose**
As part of the work to display all inspections for a BCMI Mine we need to link records using the projectName field. For EMLI this is straightforward but for Environmental Management Act records from EPD this is trickier. 

**Acceptance Criteria**
- When a record has a valid sourceID and is not an unauthorized discharge then link the record to the correct mine using the lookup table.

**Additional context**
- AMS (The source system for these records in EPD) can be found here https://j200.gov.bc.ca/pub/ams/Default.aspx?PossePresentation=ApplicationStatusSearch

![Image](https://github.com/user-attachments/assets/b26675da-9f27-4b67-aca4-e2bfa9c87fc1)

**Comment by Keegnan** [comment]
Was entered into the incorrect (GWELLS) repo. Recreated ticket in the NRPTI Repo.
