### ISSUE TITLE
investigate wally maintenance needs

### ISSUE THREAD

**Issue by jakemorr** [bcgov/gwells#2309]
**Problem Description** 
**In order to** provide the service owner with a full picture of what risks are presnet should Wally be left unsupported, a developer **needs to** look into the Wally Code and make a list of any unsupported versions of tools or frameworks Wally uses and their dependencies.

**Solution Needs**
- a list of updates and techdebt that are outstanding for Wally catagorized into: Critical, Should do, and optional maintenance activities.
- this should include stuff like cert renewals, updates, security risks, pipeline requirements (Deployconfig change coming)

**Timebox**
- This is a high priority task it might be worth having 2 devs work on this so it can be completed before the end of the sprint. 

**Additional Context**
- Wally does not have funding and our findings here are to help the service owner form a justification to get some funds for maintaining the application. 
-  one/two sentence response for each maintenance config (ie "if this is not done ______ could happen")

**Comment by Keegnan** [comment]
Will need to be put into the correct repo. Also make sure this document is uploaded to our Confluence space once finished.

**Comment by dallascrichmond** [comment]
Link to Confluence page: https://apps.nrs.gov.bc.ca/int/confluence/display/SUSTEAM/Wally+Maintenance+Needs
