### ISSUE TITLE
Advice/Help needed: To pull owner name column out of GWELLS for wells within a specified watershed

### ISSUE THREAD

**Issue by QSu-2023** [bcgov/gwells#2318]
A regional hydrogeologist is trying to find "unauthorized use" in a specified watershed (within Koksilah watershed boundary) by checking "owner name" of the domestic use wells (intended water use = private domestic) in this area. If the owner’s name is a company rather than an individual, it is likely an unauthorized use.

- He couldn’t acquire “owner name” because it is not included in the well download from the well search page. 

- He can add “owner name” column using “add/remove column” button, and he can’t restrict the search results by the water shed boundary. 

- Using ArcGIS, he found the “owner name” under surname field in the BCGW.sde in the WHSE_WATER_MANAGEMENT.GW_WELLS_WRBC_MVW table, but this column has no data or update for WTN > 117241. It is likely this field was retired and there is no data entry for it though well report submitting or editing lately.

- In DataBC, it is likely that the “owner name” is not provided. 

It is likely he needs a well table that contains both coordinates and  owner name (probably other well information if needed) so that he can use the coordinates/ArcGIS to filter out wells within a watershed boundary. If there are no better choices, maybe the sustainment team can help him do a search at the backend to generate a table for his needs. For details, it is recommended to talk directly to him. Please contact Su for name/contact. 

check if this is possible within GWELLS UI

Thanks!

**Comment by fergmac** [comment]
The CSV for WTN's to Owner Full Name was sufficient.
